server:
  port: 3333

spring:
  application:
    name:  activity-test
  redis:
    database: 5
    host: node.td-k8s.com
    port: 1379
    password: mWRK6joVy5No
    timeout: 10ms
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jm?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456a

mybatis:
  type-aliases-package: com.test.jm.dto
  mapper-locations: classpath:mappers/*.xml
test:
  appname: 123a
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql