server:
  port: 3333

spring:
  application:
    name:  activity-test
  redis:
    database: 5
    host: node.td-k8s.com
    port: 1379
    password: mWRK6joVy5No
    timeout: 10ms

test:
  appname: 123456a