server:
  port: 3333

spring:
  application:
    name:  activity-test
  redis:
    database: 5
    host: node.td-k8s.com
    port: 1379
    password: mWRK6joVy5No
    timeout: 10ms
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.100.12.118:3306/td_activity?useUnicode=true&characterEncoding=utf8
    username: test
    password: WCpnhpTrQ6EppHW+

mybatis:
  type-aliases-package: com.test.jm.dto
  mapper-locations: classpath:mappers/*.xml
test:
  appname: 123456a